FROM apache/airflow:2.10.5-python3.10

USER root

# ติดตั้ง Java (OpenJDK 17) เพื่อรองรับการทำงานของ PySpark
RUN apt-get update && \
    apt-get install -y openjdk-17-jre-headless procps curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH="${JAVA_HOME}/bin:${PATH}"

USER airflow

# ติดตั้ง Python Dependencies สำหรับ ETL/Spark/MinIO
COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt